version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    env_file:
      - docker/variables.env
    ports:
      - "15431:5432"
    networks:
      - housingdb
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: api
    # command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "-t", "300", "--", "npm", "run", "start"]
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "-t", "300", "--", "npm", "run", "dev"]
    # command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "-t", "300", "--", "npm", "run", "test"]
    # command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "-t", "300", "--", "npm", "run", "hold"]
    volumes:
      - ./:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "23084:8081"
    env_file:
      - docker/variables.env
    links:
      - postgres
    networks:
      - housingdb
    depends_on:
      - postgres
networks:
  default:
    driver: bridge
  housingdb:
    driver: bridge
