version: '3'
services:
  lab:
    build: .
    hostname: lab
    # command: npm run start
    command: npm run dev
    # command: npm run test
    # command: npm run hold
    volumes:
      - ..:/usr/src/api
    ports:
      - "23084:8081"
    env_file:
      - variables.env
networks:
  default:
    driver: bridge
